-- Schema for the family reimbursement tracker
CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL,
  monthly_budget DECIMAL(12,2) NOT NULL,
  note VARCHAR(500) DEFAULT NULL,
  secret_code VARCHAR(50) NOT NULL,
  admin_code VARCHAR(50) NOT NULL,
  started TINYINT(1) NOT NULL DEFAULT 1,
  paused TINYINT(1) NOT NULL DEFAULT 0,
  archived TINYINT(1) NOT NULL DEFAULT 0,
  milestones VARCHAR(100) NOT NULL DEFAULT '25,50,75,100',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  type ENUM('versement','contestation') NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  note VARCHAR(300) DEFAULT NULL,
  occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_transactions_project
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  INDEX idx_transactions_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
